### ISSUE TITLE
Unknown person

### ISSUE THREAD

**Issue by stepenik** [povilasb/face-recognition#1] opened 2017-01-22 17:37 UTC
Hi,
This is cool project nice thumbs up

If you have one person in training_images file and new person come to the camere this new person have same name like first person.

I think it is better solution if you dont have new person in training_images this news person have name "Unknown".

**Comment by povilasb** [comment] 2017-01-22 18:38
Indeed this would be better.

The thing is, the way recognition works is that, when you train algorithm with you face a vector is built.
Then every detected face in a camera frame is converted to another vector.
Then those vectors are compared to the trained ones.
The algorithm finds the closes vector (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) to the ones in camera and this is how we get a label for a given face.

But when you have only one trained vector, you will always get the same label/name for unknown faces.

The simplest solution would be to use some threshold when comparing face vectors.
I'm not sure, but as far as I remember I already tried that months before.
But it resulted in not detecting my face at all :/

**Comment by stepenik** [comment] 2017-01-22 19:06
https://www.dropbox.com/sh/9678cf7kefwoqrp/AABoh-tqBu_aqBm8JZV1F3Jda?dl=0

https://m.youtube.com/watch?v=Sk2rzJYGhqE

I am found this video. In this video you can see "Unknown" persons. Do you know how to implement this code in your code.  Author of this video is post code in dropbox.

**Comment by povilasb** [comment] 2017-01-22 20:01
Yes.
The changes should be made in https://github.com/povilasb/eigenfaces/blob/11f93098eabd4f16d21f40eb5173628eec9d6bef/eigenfaces.py

Take a look at function `predict_face` at line 67.
To understand what is going on you can print min class and min distance. E.g.:
```
print(min_class, min_distance)
return min_class
```

You'll see something like this:
```
('Povilas', 3369.1768)
('Povilas', 2795.877)
('Povilas', 2966.9185)
('Povilas', 3067.6204)
('Povilas', 2952.7019)
('Povilas', 3139.6304)
('Povilas', 3234.323)
('Povilas', 3184.5798)
('Povilas', 3093.8198)
```

Now what you have to change is check if `min_distance` is larger than your threshold, if it is, return "Unknown" as a label insted of `min_class`.

Now I don't know the practical `min_distance` threshold.
You'll have to find it yourself by testing it.

**Comment by stepenik** [comment] 2017-01-24 14:15
Hi, 
I tried without success.

I am found this post
http://answers.opencv.org/question/4604/help-opencv-facerecognition-can-not-predicte-new-face/

> ("threshold", 3000.0);

But I think this is not correct.

In comment you can see something like this

> Others set the threshold as the maximum value of minimum Euclidean distances of each face from other faces In general case, the threshold varies according to illuminations,faces background,translations etc.

What you think about this with Euclidan distance

**Comment by stepenik** [comment] 2017-01-24 15:06
I am maybe found. 

https://github.com/rragundez/PyData/blob/master/start_face_recon_app.py#L110

Thix XML change with your XML
and threshold = 4000

What you think about this ?

**Comment by povilasb** [comment] 2017-03-13 08:20
I'm not sure, have you tried it?

**Comment by stepenik** [comment] 2017-03-13 09:38
Yes I am tried. This works great in same environment, for example if you  make 10 screenshoot by day and make detection by day this works great. But if you make 10 screenshoot by day and make detection by night (with home lamp in room) this not works great. Or you make 10 screenshoots by night and make detection by day this not works great.

**Comment by povilasb** [comment] 2017-03-13 10:19
Well in this case the problem is not thresholding.
It's the algorithm itself.
Basically eigenfaces algorithm compares the pixel values.
And when there's different lightning, we have different pixel values.
Thus we suffer from imprecise predictions.
I guess in this case we can't do much more to fix this, except to change the prediction algorithm to something more sophisticated.
But curreenly this is out of my knowledege :/

**Comment by stepenik** [comment] 2017-03-13 10:31
Yes this is so hard look this on PyData conference 2016. This algoritham have same problem with lighting

https://youtu.be/MDaZtJPv3Ik?t=1h2m12s and look video another 2 minutes.

**Comment by povilasb** [comment] 2017-03-13 11:44
I guess a more robust solution should not work with pixels but instead should try to extract the face features and relations with each other.
E.g. we could  detect eyes, nose, cheeks and mouth. Then we could build vectors describing the relations between different parts of face. And those vectors could be the training data for machine learning algorithm.
http://cmp.felk.cvut.cz/~uricamic/flandmark/

Another, way easier, solution could still be using eigenfaces. But before training/predicting with eigenfaces we try applying edge detection for pictures.
E.g. https://en.wikipedia.org/wiki/Canny_edge_detector

**Comment by stepenik** [comment] 2017-03-15 16:51
Do you know how to adapt this project like that.

From main class send picture to algorithm and algorithm return to main class name of detected person.

**Comment by povilasb** [comment] 2017-04-13 12:19
Well, you should adapt `FaceDetector` class (https://github.com/povilasb/face-recognition/blob/master/src/gfx.py#L61) to a new algorithm.
Currently it uses the eigenfaces
```
self.clf = EigenFaces()
```

If you had another implementation, basically you would swap eigenfaces classifier with your more sophisticated one.

**Comment by povilasb** [comment] 2017-04-24 18:11
You should take a look at: http://www.pyimagesearch.com/2017/04/03/facial-landmarks-dlib-opencv-python/

**Comment by stepenik** [comment] 2017-04-24 20:04
Thank you man nice post. I will check 👍

**Comment by stepenik** [comment] 2017-07-23 20:16
Hi @povilasb I am test this new code on my RPI3 but every time I had error... Do you know what was problem

```
File 'main.py', line 14 in take_training_photos
for face in webcam.capture().faces():
AttributeError: 'NoneType' object has no attribute 'faces'
```
I am found your code is good but problem is with PiCamera

https://stackoverflow.com/questions/27950013/i-am-trying-make-the-raspberry-pi-camera-work-with-opencv

**Comment by stepenik** [comment] 2017-07-31 11:24
Hi @povilasb you can test new local binary pattern cascade https://github.com/opencv/opencv/blob/master/data/lbpcascades/lbpcascade_frontalface_improved.xml

This is faster algorithm then haar_cascade.

**Comment by stepenik** [comment] 2017-08-04 15:24
HI @povilasb,
why some pictures is not saved when you make train.
For example if you make 10 screenshoot 5 is saved, 5 is not saved.

**Comment by povilasb** [comment] 2017-08-05 19:23
@stepenik I'm not actively developing this solution because I don't find it to work well in practice.
Anyway, if you made a PR with binary pattern cascades or anything else, I'd be glad to accept it :)

Regarding the "AttributeError: 'NoneType' object has no attribute 'faces'" problem, there's this function [webcam.capture()](https://github.com/povilasb/face-recognition/blob/master/facerecognition/webcam.py#L11) which returns None if opening webcam fails.
I should actually fail fast in such case and throw an exception.
But I don't know the reason why it fails to open the webcam in the first place.

Also, it has happened to me too when not all training images are saved. I'm not sure what's the problem in this case. It could also be something wrong with the webcam.

Btw, could you please open separate issues for every different problem in the future?
This makes it easier to communicate and track the issues.

**Comment by povilasb** [comment] 2019-02-01 10:35
There's been a lot of discussions on different problems. I'm closing the issue. Please reraise any specific issues :)

**Closed as completed by povilasb** 2019-02-01 10:35 UTC
